<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.baomibing</groupId>
  <artifactId>snapper-standalone</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>snapper-standalone</name>
  <url>https://gitee.com/ifrog/snapper-standalone.git</url>
  <description>Standalone version for snapper</description>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven-assembly-plugin.version>3.3.0</maven-assembly-plugin.version>
    <maven-dependency-plugin.version>3.1.2</maven-dependency-plugin.version>
    <maven-jar-plugin.version>3.2.0</maven-jar-plugin.version>
    <maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>
    <maven-surefire-plugin.version>3.0.0-M5</maven-surefire-plugin.version>
    <maven-resources-plugin.version>3.2.0</maven-resources-plugin.version>
    <maven-javadoc-plugin.version>3.2.0</maven-javadoc-plugin.version>
    <maven-source-plugin.version>3.2.1</maven-source-plugin.version>
    <maven-clean-plugin.version>3.1.0</maven-clean-plugin.version>
    <maven-install-plugin.version>3.0.0-M1</maven-install-plugin.version>
    <maven-release-plugin.version>3.0.0-M1</maven-release-plugin.version>
    <maven-deploy-plugin.version>3.0.0-M1</maven-deploy-plugin.version>
    <maven-war-plugin.version>3.3.1</maven-war-plugin.version>
    <maven-release-plugin.version>3.0.0-M1</maven-release-plugin.version>
    <maven-build-helper-plugin.version>3.3.0</maven-build-helper-plugin.version>

    <java.version>1.8</java.version>

    <lombok.version>1.18.26</lombok.version>
    <snapper-dependence.version>3.3.0</snapper-dependence.version>
    <snapper-flow.version>1.0.0</snapper-flow.version>
    <spring.boot.version>2.6.14</spring.boot.version>
    <spring.cloud.version>2021.0.4</spring.cloud.version>
  </properties>

  <build>
    <finalName>${project.name}</finalName>
    <filters>
      <filter>src/main/envs/env-${env}.properties</filter>
    </filters>
    <!--配置资源文件过滤，如果有其他需要打包的资源，需要重载此配置节 -->
    <directory>target</directory>
    <outputDirectory>target/classes</outputDirectory>
    <testOutputDirectory>target/test-classes</testOutputDirectory>
    <sourceDirectory>src/main/java</sourceDirectory>
    <!--        <testSourceDirectory>src/main/test</testSourceDirectory>-->
    <resources>
      <!-- 将dirctory目录下的文件复制到targetPath下 -->
      <resource>
        <targetPath>${project.build.directory}/classes</targetPath>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
        <includes>
          <include>*.xml</include>
          <include>*.yml</include>
          <include>*.properties</include>
        </includes>
      </resource>
      <resource>
        <targetPath>${project.build.directory}/classes</targetPath>
        <directory>src/main/resources</directory>
        <filtering>false</filtering>
        <includes>
          <include>**/.groovy</include>
          <include>**/*.docx</include>
          <include>**/*.txt</include>
          <include>**/*.sql</include>
        </includes>
      </resource>
      <!-- mapp/xml中的mybatis xml 同样打到jar中 -->
      <resource>
        <directory>src/main/java</directory>
        <filtering>false</filtering>
        <includes>
          <include>**/*.xml</include>
        </includes>
      </resource>
      <resource>
        <directory>${basedir}/src/main/docker</directory>
        <targetPath>${basedir}/target</targetPath>
        <filtering>true</filtering>
        <includes>
          <include>**/*.sh</include>
        </includes>
      </resource>
      <resource>
        <directory>${basedir}/src/main/docker</directory>
        <targetPath>${basedir}/target</targetPath>
        <filtering>false</filtering>
        <includes>
          <include>**/*</include>
        </includes>
      </resource>
    </resources>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
          <version>${spring.boot.version}</version>
          <configuration>
            <finalName>${project.build.finalName}</finalName>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>repackage</goal>
              </goals>
            </execution>
          </executions>
        </plugin>


        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>${maven-resources-plugin.version}</version>
          <configuration>
            <useDefaultDelimiters>true</useDefaultDelimiters>
            <propertiesEncoding>${project.build.sourceEncoding}</propertiesEncoding>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler-plugin.version}</version>
          <configuration>
            <source>${java.version}</source>
            <target>${java.version}</target>
            <encoding>UTF-8</encoding>
            <compilerArgs>
              <arg>-parameters</arg>
            </compilerArgs>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>${maven-dependency-plugin.version}</version>
          <executions>
            <execution>
              <phase>package</phase>
              <goals>
                <goal>copy-dependencies</goal>
              </goals>
              <configuration>
                <outputDirectory>${project.build.directory}/lib</outputDirectory>
              </configuration>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-install-plugin</artifactId>
          <version>${maven-install-plugin.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <mainClass>com.baomibing.SnapperServerBootstrap</mainClass>
          <includeSystemScope>true</includeSystemScope>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

  <dependencies>

    <dependency>
      <groupId>com.baomibing</groupId>
      <artifactId>snapper-security-standalone</artifactId>
    </dependency>

<!--    <dependency>-->
<!--      <groupId>com.baomibing</groupId>-->
<!--      <artifactId>snapper-flow</artifactId>-->
<!--      <exclusions>-->
<!--        <exclusion>-->
<!--          <groupId>com.alibaba.cloud</groupId>-->
<!--          <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>-->
<!--        </exclusion>-->
<!--      </exclusions>-->
<!--    </dependency>-->

    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>

    <!--热加载-->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <scope>runtime</scope>
      <optional>true</optional>
    </dependency>


  </dependencies>

  <dependencyManagement>
    <dependencies>

      <dependency>
        <groupId>com.baomibing</groupId>
        <artifactId>snapper-security-standalone</artifactId>
        <version>${snapper-dependence.version}</version>
      </dependency>

<!--      <dependency>-->
<!--        <groupId>com.baomibing</groupId>-->
<!--        <artifactId>snapper-flow</artifactId>-->
<!--        <version>${snapper-flow.version}</version>-->
<!--      </dependency>-->

      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring.boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring.cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>${lombok.version}</version>
      </dependency>

    </dependencies>
  </dependencyManagement>

  <repositories>
    <repository>
      <id>maven-snapper</id>
      <name>maven-snapper</name>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <url>http://112.124.66.115:8081/repository/maven-local/</url>
    </repository>

    <repository>
      <id>maven-proxy</id>
      <name>maven-proxy</name>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <url>https://s01.oss.sonatype.org/content/groups/public/</url>
    </repository>

    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/libs-milestone</url>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>maven-proxy</id>
      <url>http://maven.aliyun.com/nexus/content/groups/public</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>


  <profiles>
    <!-- 本地环境 -->
    <profile>
      <id>local</id>
      <properties>
        <env>local</env>
      </properties>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
    </profile>

    <!-- 测试环境 -->
    <profile>
      <id>test</id>
      <properties>
        <env>test</env>
      </properties>
    </profile>

    <!-- 正式环境 -->
    <profile>
      <id>pub</id>
      <properties>
        <env>pub</env>
      </properties>
    </profile>

  </profiles>
</project>
